name: Zusammenbau
on: 
 push:
  branches: [main]
 pull_request: 
  branches: [main]

jobs:
 build_Linux:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v3

  - name: Zusammenmachung Solver 
    run: cmake ${{github.workspace}}/solver_application/ -B ${{github.workspace}}/solver_application/build
 
  - name: Bau Solver
    run: cmake --build ${{github.workspace}}/solver_application/build

