name: CPack

on:
 push:
   tags:
     - v**

jobs: 

  build_packages_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Solver cmake
      run: cmake ${{github.workspace}}/solver_application -B ${{github.workspace}}/solver_application/build -D PRINT_VERSION=${GITHUB_REF_NAME#v}

set(CPACK_PACKAGE_CONTACT navi1301@gmail.com)
set(CPACK_PACKAGE_VERSION ${PRINT_VERSION})

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "test")

set(CPACK_SOURCE_IGNORE_FILES 
"\\\\.cmake;/build/;/.git/;/.github/"
)


    - name: Solver build
      run: cmake --build ${{github.workspace}}/solver_application/build

    - name: Package build
      run: cmake --build ${{github.workspace}}/solver_application/build --target package

    - name: Pack source build
      run: cmake --build ${{github.workspace}}/solver_application/build --target package_source

    - name: Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: "build/*.deb,build/*.rpm,build/*.tar.gz,build/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
