name: CPack

on:
 push:
   tags:
     - v**

jobs: 

  build_packages_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Solver cmake
      run: cmake ${{github.workspace}}/solver_application -B ${{github.workspace}}/solver_application/build -D PRINT_VERSION=${GITHUB_REF_NAME#v}

    - name: Solver build
      run: cmake --build ${{github.workspace}}/solver_application/build

    - name: Package build
      run: cmake --build ${{github.workspace}}/solver_application/build --target package

    - name: Pack source build
      run: cmake --build ${{github.workspace}}/solver_application/build --target package_source

    - name: Release
      uses: ncipollo/release-action@v1.10.0

      with:
        artifacts: "build/*.deb,build/*.tar.gz,build/*.zip"
        token: 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 
