name: msi
on:
 push:
   tags:
     - g**

jobs:
  build_packages_msi:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    -  name: Build MSI
       run: |
         cd solver_application
         mkdir build && cd build
         cmake -DGENERATOR=BIN ..
         cmake --build .
         cpack -C CPackConfig.cmake -G WIX

    - name: Release
      uses: ncipollo/release-action@v1.10.0 

      with:
        artifacts: "solver_application/build/*.msi"
        token: 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
#2
